/*
 * Generated by XDoclet - Do not edit!
 */
package hub.sam.mof.reflection.server.ejb;

/**
 * Home interface for ServerObject.
 */
public interface ServerObjectHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServerObject";
   public static final String JNDI_NAME="ejb/ServerObject";

   public hub.sam.mof.reflection.server.ejb.ServerObject findByPrimaryKey(java.util.List id)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
