/*
 * Generated by XDoclet - Do not edit!
 */
package hub.sam.mof.reflection.server.ejb;

/**
 * Home interface for ServerReflectiveCollection.
 */
public interface ServerReflectiveCollectionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServerReflectiveCollection";
   public static final String JNDI_NAME="ejb/ServerReflectiveCollection";

   public hub.sam.mof.reflection.server.ejb.ServerReflectiveCollection findByPrimaryKey(java.util.List id)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
