/*
 * Generated by XDoclet - Do not edit!
 */
package hub.sam.mof.reflection.server.ejb;

/**
 * Home interface for ServerExtent.
 */
public interface ServerExtentHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServerExtent";
   public static final String JNDI_NAME="ejb/ServerExtent";

   public hub.sam.mof.reflection.server.ejb.ServerExtent findByPrimaryKey(java.util.List id)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
