
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Nov 30 14:21:03 GMT 2004
//----------------------------------------------------

package org.oslo.ocl20.syntax.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 34;
  public static final int INT_MOD = 36;
  public static final int LEFT_BRK = 56;
  public static final int ORDERED_SET = 16;
  public static final int TUPLE_TYPE = 18;
  public static final int GE = 29;
  public static final int TUPLE = 17;
  public static final int UMINUS = 32;
  public static final int COLON_COLON = 53;
  public static final int XOR = 23;
  public static final int INTEGER = 62;
  public static final int LEFT_BRA = 57;
  public static final int INV = 7;
  public static final int MINUS_GT = 61;
  public static final int INIT = 5;
  public static final int PRE = 9;
  public static final int MINUS = 31;
  public static final int INT_DIVIDE = 35;
  public static final int BAR = 48;
  public static final int SEMICOLON = 47;
  public static final int NOT = 37;
  public static final int AND = 21;
  public static final int LT = 26;
  public static final int IN = 39;
  public static final int OR = 22;
  public static final int COMMA = 44;
  public static final int IMPLIES = 20;
  public static final int BAG = 13;
  public static final int COLLECTION = 15;
  public static final int DOT_DOT = 52;
  public static final int UP = 49;
  public static final int PLUS = 30;
  public static final int IF = 40;
  public static final int DOT = 45;
  public static final int CONTEXT = 4;
  public static final int LE = 28;
  public static final int EOF = 0;
  public static final int TRUE = 65;
  public static final int error = 1;
  public static final int DERIVE = 6;
  public static final int UNDEFINED = 67;
  public static final int EQ = 24;
  public static final int RIGHT_PAR = 58;
  public static final int ITERATE = 19;
  public static final int REAL = 63;
  public static final int ENDPACKAGE = 3;
  public static final int TIMES = 33;
  public static final int COLON = 46;
  public static final int ENDIF = 43;
  public static final int ELSE = 42;
  public static final int POST = 10;
  public static final int PACKAGE = 2;
  public static final int RIGHT_BRK = 59;
  public static final int LET = 38;
  public static final int THEN = 41;
  public static final int BODY = 11;
  public static final int NE = 25;
  public static final int STRING = 64;
  public static final int QUESTION = 51;
  public static final int DEF = 8;
  public static final int SEQUENCE = 14;
  public static final int RIGHT_BRA = 60;
  public static final int AT = 50;
  public static final int SIMPLE_NAME = 68;
  public static final int FALSE = 66;
  public static final int LEFT_PAR = 55;
  public static final int GT = 27;
  public static final int SET = 12;
  public static final int UP_UP = 54;
}

