/**
 *
 *  Class ConstraintKind.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:48:55
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.contexts;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface ConstraintKind
extends
	SemanticsElement
{

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
