/**
 *
 *  Class ConstraintKind$Class.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:48:57
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.contexts;

import org.oslo.ocl20.semantics.SemanticsVisitable;
import org.oslo.ocl20.semantics.SemanticsVisitor;
public class ConstraintKind$Class
implements
    ConstraintKind,
    SemanticsVisitable
{
	/** The 'INIT' enumerator */
	public static final ConstraintKind INIT = new ConstraintKind$Class();
	/** The 'DERIVE' enumerator */
	public static final ConstraintKind DERIVE = new ConstraintKind$Class();
	/** The 'INV' enumerator */
	public static final ConstraintKind INV = new ConstraintKind$Class();
	/** The 'DEF' enumerator */
	public static final ConstraintKind DEF = new ConstraintKind$Class();
	/** The 'PRE' enumerator */
	public static final ConstraintKind PRE = new ConstraintKind$Class();
	/** The 'POST' enumerator */
	public static final ConstraintKind POST = new ConstraintKind$Class();
	/** The 'BODY' enumerator */
	public static final ConstraintKind BODY = new ConstraintKind$Class();
	/** Default constructors */
	protected ConstraintKind$Class() {
	}

	/** Overrride toString */
	public String toString() {
		return "ConstraintKind";
	}
	/** Clone the object */
	public Object clone() {
		ConstraintKind$Class obj = new ConstraintKind$Class();
		return obj;
	}

	/** Accept the visitor */
	public Object accept(SemanticsVisitor v, Object obj) {
		return v.visit(this, obj);
	}
}
