/**
 *
 *  Class Constraint.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:48:56
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.contexts;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface Constraint
extends
    SemanticsElement
{

	/** Get the 'name' from 'Constraint' */
	public String getName();
	/** Set the 'name' from 'Constraint' */
	public void setName(String name);

	/** Get the 'kind' from 'Constraint' */
	public ConstraintKind getKind();
	/** Set the 'kind' from 'Constraint' */
	public void setKind(ConstraintKind kind);

	/** Get the 'bodyExpression' from 'Constraint' */
	public org.oslo.ocl20.semantics.model.expressions.OclExpression getBodyExpression();
	/** Set the 'bodyExpression' from 'Constraint' */
	public void setBodyExpression(org.oslo.ocl20.semantics.model.expressions.OclExpression bodyExpression);

	/** Get the 'defProperty' from 'Constraint' */
	public org.oslo.ocl20.semantics.bridge.Property getDefProperty();
	/** Set the 'defProperty' from 'Constraint' */
	public void setDefProperty(org.oslo.ocl20.semantics.bridge.Property defProperty);

	/** Get the 'context' from 'Constraint' */
	public ContextDeclaration getContext();
	/** Set the 'context' from 'Constraint' */
	public void setContext(ContextDeclaration context);

	/** Get the 'defOperation' from 'Constraint' */
	public org.oslo.ocl20.semantics.bridge.Operation getDefOperation();
	/** Set the 'defOperation' from 'Constraint' */
	public void setDefOperation(org.oslo.ocl20.semantics.bridge.Operation defOperation);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
