/**
 *
 *  Class ContextDeclaration.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:48:55
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.contexts;

import java.util.List;

import org.oslo.ocl20.semantics.SemanticsElement;


public interface ContextDeclaration
extends
    SemanticsElement
{
	/** Get the 'referredNamespace' from 'ContextDeclaration' */
	public org.oslo.ocl20.semantics.bridge.Namespace getReferredNamespace();
	/** Set the 'referredNamespace' from 'ContextDeclaration' */
	public void setReferredNamespace(org.oslo.ocl20.semantics.bridge.Namespace referredNamespace);

	/** Get the 'constraint' from 'ContextDeclaration' */
	public List getConstraint();
	/** Set the 'constraint' from 'ContextDeclaration' */
	public void setConstraint(List constraint);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
