/**
 *
 *  Class PropertyContextDecl.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:48:56
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.contexts;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface PropertyContextDecl
extends
    SemanticsElement,
    ContextDeclaration
{

	/** Get the 'referredProperty' from 'PropertyContextDecl' */
	public org.oslo.ocl20.semantics.bridge.Property getReferredProperty();
	/** Set the 'referredProperty' from 'PropertyContextDecl' */
	public void setReferredProperty(org.oslo.ocl20.semantics.bridge.Property referredProperty);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
