/**
 *
 *  Class CallAction.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:49:04
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.bridge;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface CallAction
extends
    SemanticsElement,
    ModelElement
{
	/** Get the 'operation' from 'CallAction' */
	public Operation getOperation();
	/** Set the 'operation' from 'CallAction' */
	public void setOperation(Operation operation);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
