/**
 *
 *  Class Enumeration_.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:49:05
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.bridge;

import java.util.List;

public interface EnumerationType
extends
	OclModelElementType
{
	/** Get the 'literal' from 'Enumeration_' */
	public List getLiteral();
	/** Set the 'literal' from 'Enumeration_' */
	public void setLiteral(List literal);

	/** Search for a literal with a given name */
	public EnumLiteral lookupEnumLiteral(String name);
	
	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
