/**
 *
 *  Class EnumLiteral.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:49:04
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.bridge;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface EnumLiteral
extends
    SemanticsElement,
    ModelElement,
    Property
{
	/** Get the 'enumeration' from 'EnumLiteral' */
	public EnumerationType getEnumeration();
	/** Set the 'enumeration' from 'EnumLiteral' */
	public void setEnumeration(EnumerationType enumeration);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
