/**
 *
 *  Class ModelElement.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:49:04
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.bridge;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface ModelElement
extends
    SemanticsElement
{
	/** Get the 'name' from 'ModelElement' */
	public String getName();
	/** Set the 'name' from 'ModelElement' */
	public void setName(String name);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
	
	Object getDelegate();
}
