/**
 *
 *  Class Property.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:49:05
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.bridge;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface Property
extends
    SemanticsElement,
    ModelElement
{
	/** Get the 'type' from 'Property' */
	public Classifier getType();
	/** Set the 'type' from 'Property' */
	public void setType(Classifier type);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
