/* Generated by Together */

package org.oslo.ocl20.standard.lib;

public interface OclString
    extends OclAny
{
    OclInteger size();
    OclString concat(OclString string2);
    OclString substring(OclInteger lower, OclInteger upper);
    OclInteger toInteger();
    OclReal toReal();
}
