/**
 *
 *  Class SemanticsVisitable.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:49:24
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics;

public interface SemanticsVisitable
{
	/** Accept the visitor */
	public Object accept(SemanticsVisitor v, Object obj);
}
