/**
 *
 *  Class SemanticsVisitor.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:49:23
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics;

public interface SemanticsVisitor {
    
	public Object visit(org.oslo.ocl20.semantics.model.expressions.UndefinedLiteralExp host, Object data);
	public Object visit(org.oslo.ocl20.semantics.model.expressions.TypeLiteralExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.StringType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.StringType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.VoidType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.VoidType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.BagType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.BagType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.OrderedSetType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.OrderedSetType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.BooleanType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.BooleanType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.OclAnyType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.OclAnyType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.SetType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.SetType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.OclMessageType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.OclMessageType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.RealType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.RealType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.CollectionType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.CollectionType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.TupleType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.TupleType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.IntegerType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.IntegerType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.types.SequenceType' */
	public Object visit(org.oslo.ocl20.semantics.model.types.SequenceType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.CollectionKind' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.CollectionKind host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.CallExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.CallExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.LetExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.LetExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.CollectionLiteralExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.CollectionLiteralExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.BooleanLiteralExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.BooleanLiteralExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.OclExpression' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.OclExpression host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.VariableDeclaration' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.VariableDeclaration host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.LoopExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.LoopExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.IntegerLiteralExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.IntegerLiteralExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.CollectionRange' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.CollectionRange host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.OclMessageExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.OclMessageExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.VariableExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.VariableExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.CollectionLiteralPart' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.CollectionLiteralPart host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.RealLiteralExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.RealLiteralExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.NumericalLiteralExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.NumericalLiteralExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.IterateExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.IterateExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.ModelPropertyCallExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.ModelPropertyCallExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.PropertyCallExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.PropertyCallExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.OclMessageArg' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.OclMessageArg host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.UnspecifiedValueExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.UnspecifiedValueExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.OperationCallExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.OperationCallExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.EnumLiteralExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.EnumLiteralExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.LiteralExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.LiteralExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.IfExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.IfExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.StringLiteralExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.StringLiteralExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.IteratorExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.IteratorExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.TupleLiteralExp' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.TupleLiteralExp host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.expressions.CollectionItem' */
	public Object visit(org.oslo.ocl20.semantics.model.expressions.CollectionItem host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.contexts.ConstraintKind' */
	public Object visit(org.oslo.ocl20.semantics.model.contexts.ConstraintKind host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.contexts.ContextDeclaration' */
	public Object visit(org.oslo.ocl20.semantics.model.contexts.ContextDeclaration host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.contexts.Constraint' */
	public Object visit(org.oslo.ocl20.semantics.model.contexts.Constraint host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.contexts.OperationContextDecl' */
	public Object visit(org.oslo.ocl20.semantics.model.contexts.OperationContextDecl host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.contexts.PropertyContextDecl' */
	public Object visit(org.oslo.ocl20.semantics.model.contexts.PropertyContextDecl host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.contexts.ClassifierContextDecl' */
	public Object visit(org.oslo.ocl20.semantics.model.contexts.ClassifierContextDecl host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.SendAction' */
	public Object visit(org.oslo.ocl20.semantics.bridge.SendAction host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.ModelElement' */
	public Object visit(org.oslo.ocl20.semantics.bridge.ModelElement host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.EnumLiteral' */
	public Object visit(org.oslo.ocl20.semantics.bridge.EnumLiteral host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.CallAction' */
	public Object visit(org.oslo.ocl20.semantics.bridge.CallAction host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.Signal' */
	public Object visit(org.oslo.ocl20.semantics.bridge.Signal host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.OclModelElementType' */
	public Object visit(org.oslo.ocl20.semantics.bridge.OclModelElementType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.DataType' */
	public Object visit(org.oslo.ocl20.semantics.bridge.DataType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.Namespace' */
	public Object visit(org.oslo.ocl20.semantics.bridge.Namespace host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.Environment' */
	public Object visit(org.oslo.ocl20.semantics.bridge.Environment host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.Classifier' */
	public Object visit(org.oslo.ocl20.semantics.bridge.Classifier host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.Enumeration_' */
	public Object visit(org.oslo.ocl20.semantics.bridge.EnumerationType host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.Property' */
	public Object visit(org.oslo.ocl20.semantics.bridge.Property host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.NamedElement' */
	public Object visit(org.oslo.ocl20.semantics.bridge.NamedElement host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.Operation' */
	public Object visit(org.oslo.ocl20.semantics.bridge.Operation host, Object data);
	/** Visit class 'uk.ac.kent.cs.ocl20.semantics.model.bridge.Primitive' */
	public Object visit(org.oslo.ocl20.semantics.bridge.Primitive host, Object data);
}
