/**
 *
 *  Class SemanticsElement.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:49:23
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics;

public interface SemanticsElement
	extends SemanticsVisitable
{
	/** Override toString */
	public String toString();
}
