/**
 *
 *  Class CollectionType.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:13
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.types;

import org.oslo.ocl20.semantics.SemanticsElement;
import org.oslo.ocl20.semantics.bridge.Classifier;


public interface CollectionType
extends
    SemanticsElement,
	OclAnyType
{

	/** Get the 'elementType' from 'CollectionType' */
	public org.oslo.ocl20.semantics.bridge.Classifier getElementType();
	/** Set the 'elementType' from 'CollectionType' */
	public void setElementType(org.oslo.ocl20.semantics.bridge.Classifier elementType);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
    public Classifier getBaseElementType();
}
