/**
 *
 *  Class TupleType.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:13
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.types;

import java.util.List;
import java.util.Set;

import org.oslo.ocl20.semantics.SemanticsElement;


public interface TupleType
extends
    SemanticsElement,
    org.oslo.ocl20.semantics.bridge.DataType,
    org.oslo.ocl20.semantics.bridge.Classifier,
    org.oslo.ocl20.semantics.bridge.Namespace,
    org.oslo.ocl20.semantics.bridge.ModelElement
{

	/** Get the 'partType' from 'TupleType' */
	public List getPartType();
	/** Set the 'partType' from 'TupleType' */
	public void setPartType(List partType);
	public List getNames();
	public List getTypes();

	public TupleType project(Set names);    

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
    public TupleType join(TupleType t2);

}
