/**
 *
 *  Class StringType.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:13
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.types;

import org.oslo.ocl20.semantics.SemanticsElement;
import org.oslo.ocl20.semantics.bridge.Classifier;


public interface TypeType
extends
    SemanticsElement,
    org.oslo.ocl20.semantics.bridge.Primitive,
    OclAnyType,
    org.oslo.ocl20.semantics.bridge.DataType,
    org.oslo.ocl20.semantics.bridge.Classifier,
    org.oslo.ocl20.semantics.bridge.Namespace,
    org.oslo.ocl20.semantics.bridge.ModelElement
{

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();

	public Classifier getClassifier();
}
