/*
 * Generated by XDoclet - Do not edit!
 */
package hub.sam.mof.reflection.server.ejb;

/**
 * Home interface for ServerFactory.
 */
public interface ServerFactoryHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServerFactory";
   public static final String JNDI_NAME="ejb/ServerFactory";

   public hub.sam.mof.reflection.server.ejb.ServerFactory findByPrimaryKey(java.util.List id)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
