/*
 * Generated by XDoclet - Do not edit!
 */
package hub.sam.mof.reflection.server.ejb;

/**
 * Home interface for ServerReflectiveSequence.
 */
public interface ServerReflectiveSequenceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServerReflectiveSequence";
   public static final String JNDI_NAME="ejb/ServerReflectiveSequence";

   public hub.sam.mof.reflection.server.ejb.ServerReflectiveSequence findByPrimaryKey(java.util.List id)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
