/**
 *
 *  Class BooleanLiteralExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:39
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface BooleanLiteralExp
extends
    SemanticsElement,
    LiteralExp,
    OclExpression
{

	/** Get the 'booleanSymbol' from 'BooleanLiteralExp' */
	public Boolean getBooleanSymbol();
	/** Set the 'booleanSymbol' from 'BooleanLiteralExp' */
	public void setBooleanSymbol(Boolean booleanSymbol);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
