/**
 *
 *  Class CallExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:37
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface CallExp
extends
    SemanticsElement,
    OclExpression
{

	/** Get the 'source' from 'CallExp' */
	public OclExpression getSource();
	/** Set the 'source' from 'CallExp' */
	public void setSource(OclExpression source);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
