/**
 *
 *  Class CollectionKind$Class.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:43
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsVisitable;
import org.oslo.ocl20.semantics.SemanticsVisitor;
public class CollectionKind$Class
implements
    CollectionKind,
    SemanticsVisitable
{
	/** The 'COLLECTION' enumerator */
	public static final CollectionKind COLLECTION = new CollectionKind$Class();
	/** The 'SET' enumerator */
	public static final CollectionKind SET = new CollectionKind$Class();
	/** The 'SEQUENCE' enumerator */
	public static final CollectionKind SEQUENCE = new CollectionKind$Class();
	/** The 'BAG' enumerator */
	public static final CollectionKind BAG = new CollectionKind$Class();
	/** The 'ORDERED_SET' enumerator */
	public static final CollectionKind ORDERED_SET = new CollectionKind$Class();
	/** Default constructors */
	protected CollectionKind$Class() {
	}

	/** Overrride toString */
	public String toString() {
		return "CollectionKind";
	}
	/** Clone the object */
	public Object clone() {
		CollectionKind$Class obj = new CollectionKind$Class();
		return obj;
	}

	/** Accept the visitor */
	public Object accept(SemanticsVisitor v, Object obj) {
		return v.visit(this, obj);
	}
}
