/**
 *
 *  Class CollectionLiteralExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import java.util.List;

import org.oslo.ocl20.semantics.SemanticsElement;


public interface CollectionLiteralExp
extends
    SemanticsElement,
    LiteralExp,
    OclExpression
{

	/** Get the 'kind' from 'CollectionLiteralExp' */
	public CollectionKind getKind();
	/** Set the 'kind' from 'CollectionLiteralExp' */
	public void setKind(CollectionKind kind);

	/** Get the 'parts' from 'CollectionLiteralExp' */
	public List getParts();
	/** Set the 'parts' from 'CollectionLiteralExp' */
	public void setParts(List parts);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
