/**
 *
 *  Class CollectionKind.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:36
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface CollectionKind
extends
	SemanticsElement
{

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
