/**
 *
 *  Class CollectionRange$Class.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:45
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsVisitable;
import org.oslo.ocl20.semantics.SemanticsVisitor;

public class CollectionRange$Class
implements
    CollectionRange,
    SemanticsVisitable
{
	/** Default constructor */
	public CollectionRange$Class() {
		//--- Set property 'type' from 'CollectionLiteralPart' ---
		this.type = null;
		//--- Set property 'collectionLiteralExp' from 'CollectionLiteralPart' ---
		this.collectionLiteralExp = null;
		//--- Set property 'last' from 'CollectionRange' ---
		this.last = null;
		//--- Set property 'first' from 'CollectionRange' ---
		this.first = null;
	}


	/** Property 'type' from 'CollectionLiteralPart' */
	protected org.oslo.ocl20.semantics.bridge.Classifier type;
	/** Get property 'type' from 'CollectionLiteralPart' */
	public org.oslo.ocl20.semantics.bridge.Classifier getType() {
		return type;
	}
	/** Set property 'type' from 'CollectionLiteralPart' */
	public void setType(org.oslo.ocl20.semantics.bridge.Classifier type) { 
		this.type = type;
	}

	/** Property 'collectionLiteralExp' from 'CollectionLiteralPart' */
	protected CollectionLiteralExp collectionLiteralExp;
	/** Get property 'collectionLiteralExp' from 'CollectionLiteralPart' */
	public CollectionLiteralExp getCollectionLiteralExp() {
		return collectionLiteralExp;
	}
	/** Set property 'collectionLiteralExp' from 'CollectionLiteralPart' */
	public void setCollectionLiteralExp(CollectionLiteralExp collectionLiteralExp) { 
		this.collectionLiteralExp = collectionLiteralExp;
	}

	/** Property 'last' from 'CollectionRange' */
	protected OclExpression last;
	/** Get property 'last' from 'CollectionRange' */
	public OclExpression getLast() {
		return last;
	}
	/** Set property 'last' from 'CollectionRange' */
	public void setLast(OclExpression last) { 
		this.last = last;
	}

	/** Property 'first' from 'CollectionRange' */
	protected OclExpression first;
	/** Get property 'first' from 'CollectionRange' */
	public OclExpression getFirst() {
		return first;
	}
	/** Set property 'first' from 'CollectionRange' */
	public void setFirst(OclExpression first) { 
		this.first = first;
	}

	/** Override toString */
	public String toString() {
		String strId = "CollectionRange";
		String name = null;
		try {
			java.lang.Class cls = this.getClass();
			java.lang.reflect.Method method = cls.getMethod("getName", new java.lang.Class[] {});
			name = (String) method.invoke(this, new Object[] {});
			if (name != null && name.length()==0) name = null;
		} catch (Exception e) {
		}
		if (name == null)
			return strId;
		else
			return strId+" '"+name+"'";
	}

	/** Accept 'uk.ac.kent.cs.ocl20.semantics.model.expressions.CollectionRange$Visitor' */
	public Object accept(SemanticsVisitor v, Object data) {
		return v.visit(this, data);
	}

	/** Clone the object */
	public Object clone() {
		CollectionRange$Class obj = new CollectionRange$Class();
		obj.type = type==null ? null : this.type;
		obj.collectionLiteralExp = collectionLiteralExp==null ? null : this.collectionLiteralExp;
		obj.last = last==null ? null : this.last;
		obj.first = first==null ? null : this.first;
		return obj;
	}
}
