/**
 *
 *  Class CollectionItem$Class.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:55
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsVisitable;
import org.oslo.ocl20.semantics.SemanticsVisitor;

public class CollectionItem$Class
implements
    CollectionItem,
    SemanticsVisitable
{
	/** Default constructor */
	public CollectionItem$Class() {
		//--- Set property 'type' from 'CollectionLiteralPart' ---
		this.type = null;
		//--- Set property 'collectionLiteralExp' from 'CollectionLiteralPart' ---
		this.collectionLiteralExp = null;
		//--- Set property 'item' from 'CollectionItem' ---
		this.item = null;
	}


	/** Property 'type' from 'CollectionLiteralPart' */
	protected org.oslo.ocl20.semantics.bridge.Classifier type;
	/** Get property 'type' from 'CollectionLiteralPart' */
	public org.oslo.ocl20.semantics.bridge.Classifier getType() {
		return type;
	}
	/** Set property 'type' from 'CollectionLiteralPart' */
	public void setType(org.oslo.ocl20.semantics.bridge.Classifier type) { 
		this.type = type;
	}

	/** Property 'collectionLiteralExp' from 'CollectionLiteralPart' */
	protected CollectionLiteralExp collectionLiteralExp;
	/** Get property 'collectionLiteralExp' from 'CollectionLiteralPart' */
	public CollectionLiteralExp getCollectionLiteralExp() {
		return collectionLiteralExp;
	}
	/** Set property 'collectionLiteralExp' from 'CollectionLiteralPart' */
	public void setCollectionLiteralExp(CollectionLiteralExp collectionLiteralExp) { 
		this.collectionLiteralExp = collectionLiteralExp;
	}

	/** Property 'item' from 'CollectionItem' */
	protected OclExpression item;
	/** Get property 'item' from 'CollectionItem' */
	public OclExpression getItem() {
		return item;
	}
	/** Set property 'item' from 'CollectionItem' */
	public void setItem(OclExpression item) { 
		this.item = item;
	}

	/** Override toString */
	public String toString() {
		String strId = "CollectionItem";
		String name = null;
		try {
			java.lang.Class cls = this.getClass();
			java.lang.reflect.Method method = cls.getMethod("getName", new java.lang.Class[] {});
			name = (String) method.invoke(this, new Object[] {});
			if (name != null && name.length()==0) name = null;
		} catch (Exception e) {
		}
		if (name == null)
			return strId;
		else
			return strId+" '"+name+"'";
	}

	/** Accept 'uk.ac.kent.cs.ocl20.semantics.model.expressions.CollectionItem$Visitor' */
	public Object accept(SemanticsVisitor v, Object data) {
		return v.visit(this, data);
	}

	/** Clone the object */
	public Object clone() {
		CollectionItem$Class obj = new CollectionItem$Class();
		obj.type = type==null ? null : this.type;
		obj.collectionLiteralExp = collectionLiteralExp==null ? null : this.collectionLiteralExp;
		obj.item = item==null ? null : this.item;
		return obj;
	}
}
