/**
 *
 *  Class CollectionRange.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface CollectionRange
extends
    SemanticsElement,
    CollectionLiteralPart
{

	/** Get the 'last' from 'CollectionRange' */
	public OclExpression getLast();
	/** Set the 'last' from 'CollectionRange' */
	public void setLast(OclExpression last);

	/** Get the 'first' from 'CollectionRange' */
	public OclExpression getFirst();
	/** Set the 'first' from 'CollectionRange' */
	public void setFirst(OclExpression first);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
