/**
 *
 *  Class IterateExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:41
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface IterateExp
extends
    SemanticsElement,
    LoopExp,
    CallExp,
    OclExpression
{

	/** Get the 'result' from 'IterateExp' */
	public VariableDeclaration getResult();
	/** Set the 'result' from 'IterateExp' */
	public void setResult(VariableDeclaration result);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
