/**
 *
 *  Class LetExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:38
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface LetExp
extends
    SemanticsElement,
    OclExpression
{

	/** Get the 'variable' from 'LetExp' */
	public VariableDeclaration getVariable();
	/** Set the 'variable' from 'LetExp' */
	public void setVariable(VariableDeclaration variable);

	/** Get the 'in' from 'LetExp' */
	public OclExpression getIn();
	/** Set the 'in' from 'LetExp' */
	public void setIn(OclExpression in);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
