/**
 *
 *  Class OclMessageExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import java.util.Set;

import org.oslo.ocl20.semantics.SemanticsElement;


public interface OclMessageExp
extends
    SemanticsElement,
    OclExpression
{

	/** Get the 'target' from 'OclMessageExp' */
	public OclExpression getTarget();
	/** Set the 'target' from 'OclMessageExp' */
	public void setTarget(OclExpression target);

	/** Get the 'arguments' from 'OclMessageExp' */
	public Set getArguments();
	/** Set the 'arguments' from 'OclMessageExp' */
	public void setArguments(Set arguments);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
