/**
 *
 *  Class OperationCallExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:42
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import java.util.List;

import org.oslo.ocl20.semantics.SemanticsElement;


public interface OperationCallExp
extends
    SemanticsElement,
    ModelPropertyCallExp,
    CallExp,
    OclExpression
{

	/** Get the 'referredOperation' from 'OperationCallExp' */
	public org.oslo.ocl20.semantics.bridge.Operation getReferredOperation();
	/** Set the 'referredOperation' from 'OperationCallExp' */
	public void setReferredOperation(org.oslo.ocl20.semantics.bridge.Operation referredOperation);

	/** Get the 'arguments' from 'OperationCallExp' */
	public List getArguments();
	/** Set the 'arguments' from 'OperationCallExp' */
	public void setArguments(List arguments);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
	public void setName(String opName);
}
