/**
 *
 *  Class PropertyCallExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:41
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import java.util.List;

import org.oslo.ocl20.semantics.SemanticsElement;


public interface PropertyCallExp
extends
    SemanticsElement,
    ModelPropertyCallExp,
    CallExp,
    OclExpression
{

	/** Get the 'referredProperty' from 'PropertyCallExp' */
	public org.oslo.ocl20.semantics.bridge.Property getReferredProperty();
	/** Set the 'referredProperty' from 'PropertyCallExp' */
	public void setReferredProperty(org.oslo.ocl20.semantics.bridge.Property referredProperty);

	/** Get the 'qualifiers' from 'PropertyCallExp' */
	public List getQualifiers();
	/** Set the 'qualifiers' from 'PropertyCallExp' */
	public void setQualifiers(List qualifiers);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
