/**
 *
 *  Class IntegerLiteralExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsElement;
import org.oslo.ocl20.semantics.bridge.Classifier;


public interface TypeLiteralExp
extends
    SemanticsElement,
    LiteralExp,
    OclExpression
{

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();

	public Classifier getLiteralType();
}
