/**
 *
 *  Class UnspecifiedValueExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:42
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface UnspecifiedValueExp
extends
    SemanticsElement,
    OclExpression
{

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
