/**
 *
 *  Class VariableExp.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:41
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import org.oslo.ocl20.semantics.SemanticsElement;

public interface VariableExp
extends
    SemanticsElement,
    OclExpression
{

	/** Get the 'referredVariable' from 'VariableExp' */
	public VariableDeclaration getReferredVariable();
	/** Set the 'referredVariable' from 'VariableExp' */
	public void setReferredVariable(VariableDeclaration referredVariable);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
}
