/**
 *
 *  Class VariableDeclaration.java
 *
 *  Generated by KMFStudio at 09 May 2003 17:47:40
 *  Visit http://www.cs.ukc.ac.uk/kmf
 *
 */

package org.oslo.ocl20.semantics.model.expressions;

import java.util.Set;

import org.oslo.ocl20.semantics.SemanticsElement;
import org.oslo.ocl20.semantics.bridge.ModelElement;


public interface VariableDeclaration
extends
    SemanticsElement,
    ModelElement
{

	/** Get the 'type' from 'VariableDeclaration' */
	public org.oslo.ocl20.semantics.bridge.Classifier getType();
	/** Set the 'type' from 'VariableDeclaration' */
	public void setType(org.oslo.ocl20.semantics.bridge.Classifier type);

	/** Get the 'baseExp' from 'VariableDeclaration' */
	public IterateExp getBaseExp();
	/** Set the 'baseExp' from 'VariableDeclaration' */
	public void setBaseExp(IterateExp baseExp);

	/** Get the 'initExpression' from 'VariableDeclaration' */
	public OclExpression getInitExpression();
	/** Set the 'initExpression' from 'VariableDeclaration' */
	public void setInitExpression(OclExpression initExpression);

	/** Get the 'loopExpr' from 'VariableDeclaration' */
	public LoopExp getLoopExpr();
	/** Set the 'loopExpr' from 'VariableDeclaration' */
	public void setLoopExpr(LoopExp loopExpr);

	/** Get the 'variableExp' from 'VariableDeclaration' */
	public Set getVariableExp();
	/** Set the 'variableExp' from 'VariableDeclaration' */
	public void setVariableExp(Set variableExp);

	/** Override the toString */
	public String toString();

	/** Clone the object */
	public Object clone();
	public String getName();
	public void setName(String string);
}
